### PR TITLE
Updated AerialCore msgs

### LINKED ISSUE #2: [BUG] Action.msg in the aerial_core folder
I think there is a bug in the content of the `aerialcore_msgs`, especially in the `Action.msg`. It should be

```console
# The Action for command the UAV

#Take off – localize UAV and fly to predefined safe altitude
#Fly to – fly to specified position in working area according to known model of environment
#Guide to – guide UAV to specified position with respect to position of human
#Land – safe landing on starting position with respect to known obstacles

Header header

# Action type
int8 TAKE_OFF=0
int8 FLY_TO=1
int8 GUIDE_TO=2
int8 LAND=3

# The list of points in the path.
mrs_msgs/Reference[] points 
```

So `mrs_msgs/Reference` instead of `Reference`.

Please, check it.

### PR DESCRIPTION
**Pull request by klaxalk**

### CODE REVIEW

**Comment by gsilano** [comment]
I agree with this change, even with the new service, i.e., 

```console
mrs_msgs/Action
---
bool success
string message
```

As for the name, I don't know if it makes sense to call it `AerialCoreActions' because it should be already a message of Aerial-Core type. I mean, something like `aerial_core/Action`. In this case, I think, there would be no misunderstanding with the existing messages.

Also, regarding the question: 

> Does it make sense to have it inside of mrs_msgs? We already have repos with msgs for projects like DARPA, MBZIRC or NAKI. So maybe it will be better to have it in a separate repo, something like aerialcore_msgs.

I would say yes, it makes sense because the MRS software framework will be used in the project as a reference tool to perform experiments with Unmanned Aerial Vehicles (both fixed and rotatory wings). Also, as Tomas pointed out, the number of messages should not be huge, so it is best to have everything in one place

**Comment by spurnvoj** [comment]
> As for the name, I don't know if it makes sense to call it AerialCoreActions' because it should be already a message of Aerial-Core type. I mean, something like aerial_core/Action`. In this case, I think, there would be no misunderstanding with the existing messages.

I think name `aerial_core/Action` is not possible. As I know, generated messages are always under the name of the package, where they are specified. So it doesn't matter if you put it under some subfolder such as `msg/aerial_core/Action.msg`. This message will be generated as header `mrs_msgs/Action.h`. That is why Tomas wants to have a more specific name. Also, **Action** can be a misleading name because ROS has a specific msg type named [actions](http://wiki.ros.org/actionlib). 

To have include `aerial_core/Action.h` the message has to be generated in package name **aerial_core**.

**Comment by gsilano** [comment]
Ah, ok. In this case, feel free to change it. I will update the deliverable of Aerial-Core that points to that message.

**Comment by spurnvoj** [comment]
@gsilano can we close this one too?

**Comment by gsilano** [comment]
Yes, sure. This pull request was related to #2

**Pull request closed without merging**
